import scrapy


class GeniusIDSpider(scrapy.Spider):
    name = 'genius'
    start_urls = ['https://genius.com/Ariana-grande-thank-u-next-lyrics']
    songs = ['Halsey-without-me-lyrics',
             'Mariah-carey-all-i-want-for-christmas-is-you-lyrics',
             'Travis-scott-sicko-mode-lyrics',
             'Post-malone-and-swae-lee-sunflower-lyrics',
             'Panic-at-the-disco-high-hopes-lyrics',
             'Marshmello-and-bastille-happier-lyrics',
             'Bobby-helms-jingle-bell-rock-lyrics',
             'Brenda-lee-rockin-around-the-christmas-tree-lyrics',
             'Burl-ives-a-holly-jolly-christmas-lyrics',
             'Nat-king-cole-the-christmas-song-merry-christmas-to-you-lyrics',
             'Lil-baby-and-gunna-drip-too-hard-lyrics',
             'Andy-williams-its-the-most-wonderful-time-of-the-year-lyrics',
             'Maroon-5-girls-like-you-remix-lyrics', 'Kodak-black-zeze-lyrics',
             'Gene-autry-rudolph-the-red-nosed-reindeer-lyrics',
             'Sheck-wes-mo-bamba-lyrics',
             'Gucci-mane-bruno-mars-and-kodak-black-wake-up-in-the-sky-lyrics',
             'Cardi-b-money-lyrics',
             'Dean-martin-let-it-snow-let-it-snow-let-it-snow-lyrics',
             'Benny-blanco-halsey-and-khalid-eastside-lyrics',
             'Ariana-grande-breathin-lyrics', 'Post-malone-better-now-lyrics',
             '5-seconds-of-summer-youngblood-lyrics',
             'Wham-last-christmas-lyrics', 'The-ronettes-sleigh-ride-lyrics',
             'Juice-wrld-lucid-dreams-lyrics',
             'Gene-autry-here-comes-santa-claus-right-down-santa-claus-lane-lyrics',
             'Jose-feliciano-feliz-navidad-lyrics', 'Dj-snake-taki-taki-lyrics',
             'Perry-como-theres-no-place-like-home-for-the-holidays-lyrics',
             'Flipp-dinero-leave-me-alone-lyrics',
             'Bing-crosby-and-frank-sinatra-white-christmas-lyrics',
             'Perry-como-its-beginning-to-look-a-lot-like-christmas-lyrics',
             'Meek-mill-going-bad-lyrics', '21-savage-a-lot-lyrics',
             'Ella-mai-trip-lyrics',
             'Cardi-b-bad-bunny-and-j-balvin-i-like-it-lyrics',
             'Elvis-presley-blue-christmas-lyrics',
             'Dan-shay-speechless-lyrics',
             'John-lennon-and-yoko-ono-happy-xmas-war-is-over-lyrics',
             'Darlene-love-christmas-baby-please-come-home-lyrics',
             'Kelly-clarkson-underneath-the-tree-lyrics',
             'Chuck-berry-run-rudolph-run-lyrics',
             'Imagine-dragons-natural-lyrics', 'Post-malone-wow-lyrics',
             'Khalid-and-normani-love-lies-lyrics',
             'Frank-sinatra-jingle-bells-lyrics',
             'Bazzi-beautiful-bazzi-vs-edxs-ibiza-sunrise-remix-lyrics',
             'Khalid-better-lyrics',
             'Lady-gaga-and-bradley-cooper-shallow-lyrics',
             'Katy-perry-cozy-little-christmas-lyrics',
             'Luke-combs-she-got-the-best-of-me-lyrics',
             'Lauren-daigle-the-christmas-song-lyrics',
             'Lil-wayne-uproar-lyrics', 'A-boogie-wit-da-hoodie-swervin-lyrics',
             '21-savage-cant-leave-without-it-lyrics',
             'Lauren-daigle-you-say-lyrics',
             'Ellie-goulding-and-diplo-close-to-me-lyrics',
             'Jimmie-allen-best-shot-lyrics', 'Meek-mill-dangerous-lyrics',
             'Dean-lewis-be-alright-lyrics',
             'Mitchell-tenpenny-drunk-me-lyrics',
             'A-boogie-wit-da-hoodie-startender-lyrics',
             'A-boogie-wit-da-hoodie-look-back-at-it-lyrics',
             '21-savage-all-my-friends-lyrics', 'Xxxtentacion-bad-lyrics',
             'Pardison-fontaine-backin-it-up-lyrics',
             '21-savage-break-da-law-lyrics', 'Ariana-grande-imagine-lyrics',
             'Tory-lanez-and-rich-the-kid-talk-to-me-lyrics',
             '21-savage-monster-lyrics', 'Kodak-black-calling-my-spirit-lyrics',
             'Camila-cabello-consequences-lyrics',
             'Juice-wrld-armed-and-dangerous-lyrics',
             'Xxxtentacion-and-lil-pump-arms-around-you-lyrics',
             'Mark-ronson-nothing-breaks-like-a-heart-lyrics',
             'Thomas-rhett-sixteen-lyrics', 'Dierks-bentley-burning-man-lyrics',
             'Luke-combs-beautiful-crazy-lyrics',
             'Billie-eilish-when-the-partys-over-lyrics',
             'Ava-max-sweet-but-psycho-lyrics',
             'The-chainsmokers-this-feeling-lyrics', 'Jacquees-you-lyrics',
             '21-savage-15-lyrics', 'Jason-aldean-girl-like-you-lyrics',
             '21-savage-out-for-the-night-lyrics',
             'Dustin-lynch-good-girl-lyrics',
             'French-montana-no-stylist-lyrics',
             'Billie-eilish-and-khalid-lovely-lyrics',
             '21-savage-gun-smoke-lyrics',
             'A-boogie-wit-da-hoodie-demons-and-angels-lyrics',
             '21-savage-asmr-lyrics', 'Kip-moore-last-shot-lyrics',
             'Future-and-juice-wrld-fine-china-lyrics', 'Calboy-envy-me-lyrics',
             'Shawn-mendes-lost-in-japan-lyrics',
             'Scotty-mccreery-this-is-it-lyrics',
             'Silk-city-and-dua-lipa-electricity-lyrics',
             'Lil-duval-smile-living-my-best-life-lyrics',
             'Chris-stapleton-millionaire-lyrics',
             'Lil-baby-pure-cocaine-lyrics',
             'Jordan-davis-take-it-from-me-lyrics',
             'Luke-bryan-what-makes-you-country-lyrics',
             'Travis-scott-yosemite-lyrics',
             'Russell-dickerson-blue-tacoma-lyrics',
             'Jake-owen-down-to-the-honkytonk-lyrics',
             'Lil-baby-close-friends-lyrics',
             'Lukas-graham-love-someone-lyrics',
             'Carrie-underwood-love-wins-lyrics', '6ix9ine-kika-lyrics',
             'Ski-mask-the-slump-god-nuketown-lyrics',
             'Zara-larsson-ruin-my-life-lyrics', 'Loud-luxury-body-lyrics',
             'Tyga-and-nicki-minaj-dip-lyrics', 'Nicki-minaj-good-form-lyrics',
             'Brett-young-here-tonight-lyrics', 'Midland-burn-out-lyrics',
             'Eminem-lucky-you-lyrics',
             'Benny-blanco-and-juice-wrld-roses-lyrics',
             'Xxxtentacion-whoa-mind-in-awe-lyrics',
             'Old-dominion-make-it-sweet-lyrics',
             'Billie-eilish-ocean-eyes-lyrics',
             'Billie-eilish-idontwannabeyouanymore-lyrics',
             'Chris-brown-undecided-lyrics', 'Future-crushed-up-lyrics',
             'Lil-pump-butterfly-doors-lyrics',
             'Metro-boomin-space-cadet-lyrics',
             'Youngboy-never-broke-again-valuable-pain-lyrics',
             'The-weeknd-and-gesaffelstein-lost-in-the-fire-lyrics',
             'Sam-smith-and-normani-dancing-with-a-stranger-lyrics',
             'City-girls-twerk-lyrics', 'Khalid-saturday-nights-lyrics',
             'Kehlani-nights-like-this-lyrics', 'Blueface-thotiana-lyrics',
             'Alec-benjamin-let-me-down-slowly-remix-lyrics',
             'Future-jumpin-on-a-jet-lyrics', 'Rich-the-kid-splashin-lyrics',
             'Ariana-grande-7-rings-lyrics', 'J-cole-middle-child-lyrics',
             'Logic-keanu-reeves-lyrics', 'Future-first-off-lyrics',
             'Future-never-stop-lyrics', 'Ynw-melly-mixed-personalities-lyrics',
             'Future-temptation-lyrics', 'Future-rocket-ship-lyrics',
             'Mustard-and-migos-pure-water-lyrics', 'Future-f-n-lyrics',
             'Cody-johnson-on-my-way-to-you-lyrics',
             'Ynw-melly-murder-on-my-mind-lyrics', 'Maren-morris-girl-lyrics',
             'Future-call-the-coroner-lyrics', 'Dan-shay-tequila-lyrics',
             'Yo-gotti-put-a-date-on-it-lyrics',
             'Billie-eilish-bury-a-friend-lyrics',
             'Lauv-and-troye-sivan-im-so-tired-lyrics',
             'Ella-mai-shot-clock-lyrics', 'Xxxtentacion-sauce-lyrics',
             'Jon-pardi-night-shift-lyrics', 'Marshmello-alone-lyrics',
             'Gunna-one-call-lyrics', 'Kelsea-ballerini-miss-me-more-lyrics',
             'Ariana-grande-break-up-with-your-girlfriend-im-bored-lyrics',
             'Ariana-grande-needy-lyrics', 'Ariana-grande-nasa-lyrics',
             'Ariana-grande-bloodline-lyrics', 'Ariana-grande-ghostin-lyrics',
             'Ariana-grande-fake-smile-lyrics', 'Ariana-grande-bad-idea-lyrics',
             'Ariana-grande-in-my-head-lyrics', 'Khalid-talk-lyrics',
             'Ariana-grande-make-up-lyrics',
             'The-chainsmokers-and-5-seconds-of-summer-who-do-you-love-lyrics',
             'Kacey-musgraves-rainbow-lyrics',
             'Cardi-b-and-bruno-mars-please-me-lyrics',
             'Juice-wrld-robbery-lyrics', 'Offset-red-room-lyrics',
             'Florida-georgia-line-talk-you-out-of-it-lyrics',
             'Chase-rice-eyes-on-you-lyrics', 'Zedd-and-katy-perry-365-lyrics',
             'Yk-osiris-worth-it-lyrics',
             'Riley-green-there-was-this-girl-lyrics',
             'Michael-ray-one-that-got-away-lyrics',
             'Lady-gaga-always-remember-us-this-way-lyrics',
             'Offset-legacy-lyrics', 'P-nk-walk-me-home-lyrics',
             'Lady-gaga-ill-never-love-again-extended-version-lyrics',
             'Offset-clout-lyrics', 'Offset-how-did-i-get-here-lyrics',
             'Gunna-outstanding-lyrics', 'Lil-pump-be-like-me-lyrics',
             'Gunna-3-headed-snake-lyrics', 'Gunna-wit-it-lyrics',
             'Offset-lick-lyrics',
             'Summer-walker-and-drake-girls-need-love-remix-lyrics',
             'Gunna-speed-it-up-lyrics',
             'John-mayer-i-guess-i-just-feel-like-lyrics',
             'Kane-brown-good-as-you-lyrics', 'Gunna-same-yung-nigga-lyrics',
             'Ski-mask-the-slump-god-faucet-failure-lyrics',
             'Jonas-brothers-sucker-lyrics', 'Lil-skies-i-lyrics',
             'Thomas-rhett-look-what-god-gave-her-lyrics',
             'Juice-wrld-hear-me-calling-lyrics',
             'Imagine-dragons-bad-liar-lyrics',
             'Billie-eilish-wish-you-were-gay-lyrics', '2-chainz-whip-lyrics',
             'City-girls-act-up-lyrics',
             'Lil-nas-x-and-billy-ray-cyrus-old-town-road-remix-lyrics',
             'Morgan-wallen-whiskey-glasses-lyrics',
             'Benny-blanco-tainy-selena-gomez-and-j-balvin-i-cant-get-enough-lyrics',
             '2-chainz-rule-the-world-lyrics',
             '2-chainz-momma-i-hit-a-lick-lyrics', 'Juice-wrld-empty-lyrics',
             'Juice-wrld-fast-lyrics', 'Juice-wrld-maze-lyrics',
             'Marshmello-here-with-me-lyrics', 'Khalid-my-bad-lyrics',
             'Fletcher-undrunk-lyrics', 'Lee-brice-rumor-lyrics',
             'Juice-wrld-flaws-and-sins-lyrics',
             'Lil-peep-and-ilovemakonnen-ive-been-waiting-lyrics',
             'Schoolboy-q-numb-numb-juice-lyrics',
             'Iggy-azalea-sally-walker-lyrics',
             'Joji-slow-dancing-in-the-dark-lyrics',
             'Nav-price-on-my-head-lyrics',
             'Logic-confessions-of-a-dangerous-mind-lyrics', 'Nav-tap-lyrics',
             'Polo-g-pop-out-lyrics', 'Mabel-dont-call-me-up-lyrics',
             'Bebe-rexha-last-hurrah-lyrics', 'Billie-eilish-bad-guy-lyrics',
             'Billie-eilish-xanny-lyrics',
             'Billie-eilish-you-should-see-me-in-a-crown-lyrics',
             'Billie-eilish-my-strange-addiction-lyrics',
             'Nipsey-hussle-racks-in-the-middle-lyrics',
             'Billie-eilish-all-the-good-girls-go-to-hell-lyrics',
             'Billie-eilish-i-love-you-lyrics',
             'Blake-shelton-gods-country-lyrics',
             'Billie-eilish-ilomilo-lyrics',
             'Billie-eilish-listen-before-i-go-lyrics',
             'Nipsey-hussle-double-up-lyrics',
             'Ariana-grande-and-victoria-monet-monopoly-lyrics',
             'Billie-eilish-8-lyrics',
             'Nipsey-hussle-last-time-that-i-checcd-lyrics',
             'Dababy-suge-lyrics', 'Nipsey-hussle-dedication-lyrics',
             'Jonas-brothers-cool-lyrics', 'Blackpink-kill-this-love-lyrics',
             'Khalid-and-john-mayer-outta-my-head-lyrics',
             'Khalid-dont-pretend-lyrics', 'Khalid-bad-luck-lyrics',
             'Khalid-right-back-remix-lyrics',
             'Megan-thee-stallion-big-ole-freak-lyrics',
             'Nipsey-hussle-victory-lap-lyrics', 'Bts-boy-with-luv-lyrics',
             'Lil-uzi-vert-sanguine-paradise-lyrics',
             'Five-finger-death-punch-blue-on-black-remix-lyrics',
             'Avicii-sos-lyrics', 'Lil-uzi-vert-thats-a-rack-lyrics',
             'Eli-young-band-love-aint-lyrics', 'Bts-make-it-right-lyrics',
             'Panic-at-the-disco-hey-look-ma-i-made-it-lyrics',
             'Lil-dicky-earth-lyrics', 'Beyonce-before-i-let-go-lyrics',
             'French-montana-slide-lyrics',
             'Brett-eldredge-love-someone-lyrics',
             'Nle-choppa-shotta-flow-lyrics', 'Taylor-swift-me-lyrics',
             'Schoolboy-q-floating-lyrics',
             'Schoolboy-q-and-travis-scott-chopstix-lyrics',
             'Marshmello-tyga-and-chris-brown-light-it-up-lyrics',
             'Sza-the-weeknd-and-travis-scott-power-is-power-lyrics',
             'Luke-bryan-knockin-boots-lyrics', 'P-nk-love-me-anyway-lyrics',
             'Meek-mill-24-7-lyrics', 'Yg-stop-snitchin-lyrics',
             'Shawn-mendes-if-i-cant-have-you-lyrics', 'Logic-homicide-lyrics',
             'Lizzo-truth-hurts-lyrics',
             'Luke-combs-beer-never-broke-my-heart-lyrics', 'Yg-go-loko-lyrics',
             'Pnb-rock-and-xxxtentacion-middle-child-lyrics',
             'Dan-shay-all-to-myself-lyrics', 'Bazzi-paradise-lyrics',
             'Roddy-ricch-die-young-lyrics',
             'Ed-sheeran-and-justin-bieber-i-dont-care-lyrics',
             'Jhene-aiko-triggered-freestyle-lyrics',
             'Lewis-capaldi-someone-you-loved-lyrics', 'Lizzo-juice-lyrics',
             'Tyler-the-creator-earfquake-lyrics', 'Halsey-nightmare-lyrics',
             'Dj-khaled-wish-wish-lyrics', 'Dj-khaled-higher-lyrics',
             'Dj-khaled-just-us-lyrics', 'Dj-khaled-you-stay-lyrics',
             'Tyler-the-creator-i-think-lyrics', 'Dj-khaled-celebrate-lyrics',
             'Dj-khaled-jealous-lyrics',
             'Tyler-the-creator-running-out-of-time-lyrics',
             'Tyler-the-creator-igors-theme-lyrics',
             'Tyler-the-creator-new-magic-wand-lyrics',
             'Tyler-the-creator-a-boy-is-a-gun-lyrics',
             'Tyler-the-creator-whats-good-lyrics',
             'Lady-a-what-if-i-never-get-over-you-lyrics',
             'Tyler-the-creator-puppet-lyrics',
             'Dj-khaled-weather-the-storm-lyrics',
             'Young-thug-the-london-lyrics', 'Ed-sheeran-cross-me-lyrics',
             '5-seconds-of-summer-easier-lyrics', 'Joyner-lucas-isis-lyrics',
             'Eric-church-some-of-it-lyrics',
             'Yella-beezy-quavo-and-gucci-mane-bacc-at-it-again-lyrics',
             'Jason-aldean-rearview-town-lyrics',
             'Katy-perry-never-really-over-lyrics', 'Cardi-b-press-lyrics',
             'Miley-cyrus-mothers-daughter-lyrics',
             'The-chainsmokers-and-bebe-rexha-call-you-mine-lyrics',
             'Nf-the-search-lyrics', 'John-rich-shut-up-about-politics-lyrics',
             'Bryce-vine-la-la-land-lyrics', 'Lil-tecca-ransom-lyrics',
             'Trippie-redd-under-enemy-arms-lyrics',
             'Chris-young-raised-on-country-lyrics', 'Shaed-trampoline-lyrics',
             'Chris-brown-no-guidance-lyrics',
             'Luke-combs-even-though-im-leaving-lyrics',
             'Blanco-brown-the-git-up-lyrics', 'Avicii-heaven-lyrics',
             'Future-please-tell-me-lyrics', 'Jonas-brothers-only-human-lyrics',
             'Future-xanax-damage-lyrics', 'Future-government-official-lyrics',
             'Taylor-swift-you-need-to-calm-down-lyrics',
             'Drake-money-in-the-grave-lyrics', 'Drake-omerta-lyrics',
             'Dreamville-down-bad-lyrics', 'Joji-sanctuary-lyrics',
             'Travis-scott-wake-up-lyrics',
             'Marshmello-and-a-day-to-remember-rescue-me-lyrics',
             'Ali-gatie-its-you-lyrics',
             'Justin-moore-the-ones-that-didnt-make-it-back-home-lyrics',
             'Shawn-mendes-and-camila-cabello-senorita-lyrics',
             'Lil-nas-x-panini-lyrics', 'Nicki-minaj-megatron-lyrics',
             'Lil-nas-x-and-cardi-b-rodeo-lyrics',
             'Marshmello-and-kane-brown-one-thing-right-lyrics',
             'Lil-baby-and-future-out-the-mud-lyrics',
             'Megan-thee-stallion-cash-shit-lyrics',
             'Martin-garrix-summer-days-lyrics',
             'Ed-sheeran-beautiful-people-lyrics',
             'Kygo-and-whitney-houston-higher-love-lyrics',
             'Chris-brown-dont-check-on-me-lyrics', 'Nf-when-i-grow-up-lyrics',
             'Saweetie-my-type-lyrics', 'Y2k-and-bbno-lalala-lyrics',
             'Post-malone-goodbyes-lyrics',
             'Dreamville-j-cole-and-lute-under-the-sun-lyrics',
             'Ed-sheeran-chris-stapleton-and-bruno-mars-blow-lyrics',
             'Dreamville-bas-and-jid-costa-rica-lyrics',
             'Chris-lane-i-dont-know-about-you-lyrics',
             'Ed-sheeran-and-travis-scott-antisocial-lyrics',
             'Ed-sheeran-south-of-the-border-lyrics',
             'Ed-sheeran-remember-the-name-lyrics',
             'Kenny-chesney-tip-of-my-tongue-lyrics',
             'Mustard-baguettes-in-the-face-lyrics',
             'Kane-brown-like-a-rodeo-lyrics', 'Nf-time-lyrics',
             'Carrie-underwood-southbound-lyrics', 'Beyonce-spirit-lyrics',
             'Ed-sheeran-best-part-of-me-lyrics',
             'Sam-smith-how-do-you-sleep-lyrics',
             'Quality-control-lil-baby-and-dababy-baby-lyrics',
             'Taylor-swift-the-archer-lyrics',
             'Blue-ivy-saint-jhn-beyonce-and-wizkid-brown-skin-girl-lyrics',
             'Ellie-goulding-and-juice-wrld-hate-me-lyrics',
             'Beyonce-jay-z-and-childish-gambino-mood-4-eva-lyrics',
             'Mustard-and-roddy-ricch-ballin-lyrics',
             'Rick-ross-gold-roses-lyrics',
             'Chance-the-rapper-hot-shower-lyrics',
             'Big-sean-single-again-lyrics',
             'The-chainsmokers-and-illenium-takeaway-lyrics',
             'Dierks-bentley-living-lyrics', 'Nf-leave-me-alone-lyrics',
             'Blueface-daddy-lyrics', 'Chance-the-rapper-all-day-long-lyrics',
             'Chance-the-rapper-do-you-remember-lyrics',
             'Ariana-grande-and-social-house-boyfriend-lyrics',
             'Drake-trust-issues-lyrics', 'Drake-how-bout-now-lyrics',
             'Drake-the-motion-lyrics', 'Sarah-jeffery-queen-of-mean-lyrics',
             'Drake-dreams-money-can-buy-lyrics', 'Ambjaay-uno-lyrics',
             'Drake-club-paradise-lyrics', 'Keith-urban-we-were-lyrics',
             'Tool-fear-inoculum-lyrics',
             'Cole-swindell-love-you-too-late-lyrics',
             'Drake-days-in-the-east-lyrics',
             'Brantley-gilbert-what-happens-in-a-small-town-lyrics',
             'Matt-stell-prayed-for-you-lyrics',
             'Megan-thee-stallion-hot-girl-summer-lyrics',
             'Trippie-redd-mac-10-lyrics', 'Katy-perry-small-talk-lyrics',
             'Descendants-3-cast-night-falls-lyrics', 'Wale-on-chill-lyrics',
             'Trippie-redd-snake-skin-lyrics',
             'Runaway-june-buy-my-own-drinks-lyrics', 'Lil-tjay-fn-lyrics',
             'Dababy-baby-sitter-lyrics', 'Taylor-swift-lover-lyrics',
             'Young-thug-hot-lyrics', 'Young-thug-bad-bad-bad-lyrics',
             'Normani-motivation-lyrics', 'Miley-cyrus-slide-away-lyrics',
             'Young-thug-whats-the-move-lyrics',
             'Young-thug-just-how-it-is-lyrics', 'Young-thug-surf-lyrics',
             'Young-thug-sup-mate-lyrics', 'Swae-lee-wont-be-late-lyrics',
             'Diplo-heartless-lyrics', 'Young-thug-light-it-up-lyrics',
             'Doja-cat-and-tyga-juicy-lyrics', 'Young-thug-lil-baby-lyrics',
             'Young-thug-ecstasy-lyrics',
             'Russell-dickerson-every-little-thing-lyrics',
             'Lil-tecca-did-it-again-lyrics', 'Taylor-swift-the-man-lyrics',
             'Taylor-swift-i-forgot-that-you-existed-lyrics',
             'Taylor-swift-cruel-summer-lyrics',
             'Taylor-swift-paper-rings-lyrics',
             'Taylor-swift-miss-americana-and-the-heartbreak-prince-lyrics',
             'Taylor-swift-i-think-he-knows-lyrics',
             'Lizzo-good-as-hell-lyrics', 'Taylor-swift-cornelia-street-lyrics',
             'Taylor-swift-london-boy-lyrics',
             'Taylor-swift-soon-youll-get-better-lyrics',
             'Taylor-swift-death-by-a-thousand-cuts-lyrics',
             'Taylor-swift-afterglow-lyrics', 'Taylor-swift-false-god-lyrics',
             'Summer-walker-playing-games-lyrics',
             'Taylor-swift-daylight-lyrics', 'Old-dominion-one-man-band-lyrics',
             'Taylor-swift-its-nice-to-have-a-friend-lyrics',
             'Post-malone-circles-lyrics', 'Lana-del-rey-doin-time-lyrics',
             'A-ap-rocky-babushka-boi-lyrics', 'Chris-brown-heat-lyrics',
             'Lil-tecca-out-of-luck-lyrics', 'Lil-tecca-shots-lyrics',
             'Big-sean-bezerk-lyrics', 'Chris-janson-good-vibes-lyrics',
             'For-king-and-country-god-only-knows-lyrics',
             'Maren-morris-the-bones-lyrics', 'Lil-tecca-love-me-lyrics',
             'Post-malone-take-what-you-want-lyrics',
             'Post-malone-hollywoods-bleeding-lyrics',
             'Post-malone-enemies-lyrics', 'Post-malone-saint-tropez-lyrics',
             'Post-malone-die-for-me-lyrics', 'Post-malone-on-the-road-lyrics',
             'Post-malone-a-thousand-bad-times-lyrics',
             'Post-malone-im-gonna-be-lyrics',
             'Post-malone-staring-at-the-sun-lyrics',
             'Post-malone-allergic-lyrics', 'Post-malone-myself-lyrics',
             'Post-malone-i-know-lyrics', 'Camila-cabello-liar-lyrics',
             'Post-malone-internet-lyrics', 'Camila-cabello-shameless-lyrics',
             'Youngboy-never-broke-again-self-control-lyrics',
             'Kelsea-ballerini-homecoming-queen-lyrics',
             '9lokknine-223s-lyrics',
             'Ariana-grande-miley-cyrus-and-lana-del-rey-dont-call-me-angel-charlies-angels-lyrics',
             'Nle-choppa-camelot-lyrics', 'Halsey-graveyard-lyrics',
             'Drake-behind-barz-lyrics',
             'A-boogie-wit-da-hoodie-mood-swings-lyrics',
             'Blackbear-hot-girl-bummer-lyrics', 'Luke-combs-1-2-many-lyrics',
             'Thomas-rhett-remember-you-young-lyrics', 'Dababy-intro-lyrics',
             'Maroon-5-memories-lyrics', 'Lil-mosey-stuck-in-a-dream-lyrics',
             'Dababy-bop-lyrics', 'Dababy-vibez-lyrics', 'Dababy-toes-lyrics',
             'Dababy-and-nicki-minaj-iphone-lyrics',
             'Dababy-off-the-rip-lyrics', 'Dababy-pop-star-lyrics',
             'Dababy-raw-shit-lyrics', 'Dababy-gospel-lyrics',
             'French-montana-writing-on-the-wall-lyrics',
             'Dababy-really-lyrics', 'Dababy-xxl-lyrics',
             'Dababy-prolly-heard-lyrics', 'J-hope-chicken-noodle-soup-lyrics',
             'Jon-pardi-heartache-medication-lyrics',
             'Kevin-gates-by-my-lonely-lyrics', 'Dababy-there-he-go-lyrics',
             'Travis-scott-highest-in-the-room-lyrics',
             'Dan-shay-and-justin-bieber-10000-hours-lyrics',
             'Juice-wrld-and-youngboy-never-broke-again-bandit-lyrics',
             'Summer-walker-and-usher-come-thru-lyrics',
             'Summer-walker-ill-kill-you-lyrics',
             'Summer-walker-stretch-you-out-lyrics',
             'Summer-walker-body-lyrics',
             'Summer-walker-drunk-dialing-lodt-lyrics',
             'Summer-walker-over-it-lyrics',
             'Niall-horan-nice-to-meet-ya-lyrics',
             'Quality-control-layton-greene-and-lil-baby-leave-em-alone-lyrics',
             'Summer-walker-potential-lyrics',
             'Tones-and-i-dance-monkey-lyrics', 'Harry-styles-lights-up-lyrics',
             'Youngboy-never-broke-again-lonely-child-lyrics',
             'Youngboy-never-broke-again-make-no-sense-lyrics',
             'Youngboy-never-broke-again-carter-son-lyrics',
             'Sam-hunt-kinfolks-lyrics',
             'Youngboy-never-broke-again-hot-now-lyrics',
             'Moneybagg-yo-and-megan-thee-stallion-all-dat-lyrics',
             'Youngboy-never-broke-again-in-control-lyrics',
             'Youngboy-never-broke-again-time-im-on-lyrics',
             'Youngboy-never-broke-again-rich-as-hell-lyrics',
             'Selena-gomez-lose-you-to-love-me-lyrics',
             'Internet-money-somebody-lyrics', 'Frank-ocean-dhl-lyrics',
             'Kanye-west-follow-god-lyrics',
             'Kanye-west-closed-on-sunday-lyrics', 'Kanye-west-selah-lyrics',
             'Kanye-west-on-god-lyrics', 'Selena-gomez-look-at-her-now-lyrics',
             'Kanye-west-everything-we-need-lyrics', 'Kanye-west-god-is-lyrics',
             'Kanye-west-use-this-gospel-lyrics',
             'Michael-jackson-thriller-lyrics', 'Kanye-west-every-hour-lyrics',
             'Kanye-west-water-lyrics', 'Kanye-west-hands-on-lyrics',
             'Kanye-west-jesus-is-lord-lyrics',
             'Roddy-ricch-start-wit-me-lyrics',
             'Luke-bryan-what-she-wants-tonight-lyrics',
             'Dua-lipa-dont-start-now-lyrics', 'Arizona-zervas-roxanne-lyrics',
             '21-savage-immortal-lyrics',
             'Miranda-lambert-it-all-comes-out-in-the-wash-lyrics',
             'Trippie-redd-love-me-more-lyrics',
             'Frank-ocean-in-my-room-lyrics', 'Dustin-lynch-ridin-roads-lyrics',
             'Kane-brown-for-my-daughter-lyrics', 'Danileigh-easy-lyrics',
             'Gucci-mane-big-boy-diamonds-lyrics', 'Lil-baby-woah-lyrics',
             'Rod-wave-heart-on-ice-lyrics',
             'Luke-combs-better-together-lyrics',
             'Billie-eilish-everything-i-wanted-lyrics',
             'Ant-saunders-yellow-hearts-lyrics',
             'Tory-lanez-and-t-pain-jerry-sprunger-lyrics',
             'Alicia-keys-show-me-love-lyrics', '24kgoldn-valentino-lyrics',
             'A-boogie-wit-da-hoodie-reply-lyrics',
             'Jhene-aiko-none-of-your-concern-lyrics',
             'Harry-styles-watermelon-sugar-lyrics',
             'Tory-lanez-the-take-lyrics', 'Trevor-daniel-falling-lyrics',
             'Tory-lanez-beauty-in-the-benz-lyrics',
             'Khalid-up-all-night-lyrics', 'Jason-aldean-we-back-lyrics',
             'Kane-brown-homesick-lyrics', 'Trippie-redd-death-lyrics',
             'Blake-shelton-hell-right-lyrics',
             'The-black-eyed-peas-and-j-balvin-ritmo-bad-boys-for-life-lyrics',
             'The-weeknd-heartless-lyrics',
             'Idina-menzel-and-aurora-into-the-unknown-lyrics',
             'Trippie-redd-who-needs-love-lyrics', 'Trippie-redd-6-kiss-lyrics',
             'Partynextdoor-loyal-lyrics', 'Ynw-melly-suicidal-lyrics',
             'Trippie-redd-hate-me-lyrics', 'Doja-cat-candy-lyrics',
             'Rod-wave-cuban-links-lyrics',
             'Panic-at-the-disco-into-the-unknown-panic-at-the-disco-version-lyrics',
             'Idina-menzel-and-evan-rachel-wood-show-yourself-lyrics',
             'The-weeknd-blinding-lights-lyrics',
             'Andy-williams-happy-holiday-the-holiday-season-lyrics',
             'Don-toliver-no-idea-lyrics',
             'Jonas-brothers-like-its-christmas-lyrics',
             'Roddy-ricch-tip-toe-lyrics', 'Juice-wrld-legends-lyrics',
             'Harry-styles-adore-you-lyrics', 'Roddy-ricch-the-box-lyrics',
             'Taylor-swift-christmas-tree-farm-lyrics',
             'Roddy-ricch-peta-lyrics', 'Camila-cabello-my-oh-my-lyrics',
             'Xxxtentacion-bad-vibes-forever-lyrics',
             'Fat-joe-and-dre-lord-above-lyrics',
             'Roddy-ricch-big-stepper-lyrics', 'Russ-best-on-earth-lyrics',
             'Lil-uzi-vert-futsal-shuffle-2020-lyrics',
             'Harry-styles-falling-lyrics',
             'Youngboy-never-broke-again-dirty-iyanna-lyrics',
             'Juice-wrld-let-me-know-i-wonder-why-freestyle-lyrics',
             'Blake-shelton-nobody-but-you-lyrics',
             'Nle-choppa-famous-hoes-lyrics', 'Harry-styles-cherry-lyrics',
             'Harry-styles-golden-lyrics', 'Harry-styles-she-lyrics',
             'Dean-martin-baby-its-cold-outside-lyrics',
             'Thurl-ravenscroft-youre-a-mean-one-mr-grinch-lyrics',
             'John-lennon-and-yoko-ono-happy-xmas-war-is-over-lyrics',
             'Her-slide-lyrics', 'Jackboys-and-travis-scott-out-west-lyrics',
             'Jackboys-and-sheck-wes-gang-gang-lyrics',
             'Don-toliver-had-enough-lyrics',
             'Jackboys-and-travis-scott-what-to-do-lyrics',
             'Jackboys-pop-smoke-and-travis-scott-gatti-lyrics',
             'Roddy-ricch-high-fashion-lyrics',
             'Gabby-barrett-i-hope-remix-lyrics',
             'Jimmie-allen-make-me-want-to-lyrics',
             'Ingrid-andress-more-hearts-than-mine-lyrics',
             'Riley-green-i-wish-grandpas-never-died-lyrics',
             'Jordan-davis-slow-dance-in-a-parking-lot-lyrics',
             'Noah-cyrus-and-leon-bridges-july-lyrics',
             'Justin-bieber-yummy-lyrics', 'Moneybagg-yo-u-played-lyrics',
             'Brockhampton-sugar-lyrics', 'Olivia-rodrigo-all-i-want-lyrics',
             'Carly-pearce-and-lee-brice-i-hope-youre-happy-now-lyrics',
             'Lil-tjay-20-20-lyrics', 'Doja-cat-say-so-lyrics',
             'Baby-keem-orange-soda-lyrics', 'Future-life-is-good-lyrics',
             'Lil-baby-sum-2-prove-lyrics', 'Mac-miller-good-news-lyrics',
             'Halsey-you-should-be-sad-lyrics', 'Selena-gomez-rare-lyrics',
             'Khalid-eleven-lyrics',
             'John-legend-conversations-in-the-dark-lyrics',
             'Moneybagg-yo-protect-da-brand-lyrics',
             'Eminem-juice-wrld-godzilla-lyrics',
             'Jonas-brothers-what-a-man-gotta-do-lyrics',
             'Eminem-darkness-lyrics', 'Eminem-those-kinda-nights-lyrics',
             'Eminem-unaccommodating-lyrics', 'Mac-miller-blue-world-lyrics',
             'Mac-miller-circles-lyrics', 'Eminem-you-gon-learn-lyrics',
             'Bts-black-swan-lyrics', 'Jhene-aiko-pu-y-fairy-otw-lyrics',
             'Eminem-leaving-heaven-lyrics', 'Mac-miller-complicated-lyrics',
             'Mac-miller-hand-me-downs-lyrics',
             'Eminem-premonition-intro-lyrics', 'Mac-miller-i-can-see-lyrics',
             'Eminem-in-too-deep-lyrics', 'Mac-miller-woods-lyrics',
             'Mac-miller-everybody-lyrics', 'Eminem-marsh-lyrics',
             'Eminem-no-regrets-lyrics', 'Eminem-lock-it-up-lyrics',
             'Mac-miller-surf-lyrics', 'Eminem-stepdad-lyrics',
             'Mac-miller-thats-on-me-lyrics',
             'Megan-thee-stallion-bitch-lyrics', 'Demi-lovato-anyone-lyrics',
             'Meek-mill-letter-to-nipsey-lyrics',
             'Morgan-wallen-chasin-you-lyrics',
             'Lewis-capaldi-before-you-go-lyrics', 'Jake-owen-homemade-lyrics',
             'Alicia-keys-underdog-lyrics', 'Camila-cabello-first-man-lyrics',
             'Ali-gatie-what-if-i-told-you-that-i-love-you-lyrics',
             'Brett-young-catch-lyrics', 'Garth-brooks-dive-bar-lyrics',
             'Lil-wayne-i-do-it-lyrics', 'Taylor-swift-only-the-young-lyrics',
             'Dua-lipa-physical-lyrics', 'Lil-wayne-mahogany-lyrics',
             'A-boogie-wit-da-hoodie-king-of-my-city-lyrics',
             'Lil-wayne-mama-mia-lyrics', 'Lil-wayne-funeral-lyrics',
             'Meghan-trainor-nice-to-meet-ya-lyrics',
             'Justin-bieber-get-me-lyrics', 'Justin-bieber-intentions-lyrics',
             'Nicki-minaj-yikes-lyrics',
             'Khalid-and-disclosure-know-your-worth-lyrics',
             'Lil-mosey-blueberry-faygo-lyrics', 'Joji-run-lyrics',
             'Meek-mill-believe-lyrics', 'Jack-harlow-whats-poppin-lyrics',
             'Niall-horan-no-judgement-lyrics',
             'Billie-eilish-no-time-to-die-lyrics',
             'A-boogie-wit-da-hoodie-numbers-lyrics',
             'Justin-bieber-forever-lyrics', 'Sam-smith-to-die-for-lyrics',
             'Migos-give-no-fxk-lyrics', 'Pop-smoke-dior-lyrics',
             'A-boogie-wit-da-hoodie-me-and-my-guitar-lyrics',
             'Polo-g-stunna-4-vegas-and-nle-choppa-go-stupid-lyrics',
             'A-boogie-wit-da-hoodie-might-not-give-up-lyrics',
             'A-boogie-wit-da-hoodie-thug-love-lyrics',
             'The-weeknd-after-hours-lyrics',
             'A-boogie-wit-da-hoodie-stain-lyrics',
             'Justin-bieber-come-around-me-lyrics',
             'A-boogie-wit-da-hoodie-cinderella-story-lyrics',
             'Justin-bieber-habitual-lyrics',
             'Justin-bieber-all-around-me-lyrics', 'Bts-on-lyrics',
             'Youngboy-never-broke-again-lil-top-lyrics',
             'Youngboy-never-broke-again-red-eye-lyrics',
             'Youngboy-never-broke-again-fine-by-time-lyrics',
             'Youngboy-never-broke-again-bad-bad-lyrics',
             'Youngboy-never-broke-again-knocked-off-lyrics',
             'Ashe-moral-of-the-story-remix-lyrics',
             'Youngboy-never-broke-again-rip-lil-phat-lyrics',
             'Bts-my-time-lyrics', 'Youngboy-never-broke-again-long-rd-lyrics',
             'Bts-filter-lyrics', 'Youngboy-never-broke-again-bat-man-lyrics',
             'Pop-smoke-shake-the-room-lyrics', 'Selena-gomez-feel-me-lyrics',
             'Lady-gaga-stupid-love-lyrics',
             'Lil-baby-and-gunna-heatin-up-lyrics',
             'Lil-uzi-vert-that-way-lyrics', 'Lil-baby-commercial-lyrics',
             'Lil-baby-live-off-my-closet-lyrics',
             'Lil-baby-emotionally-scarred-lyrics', 'G-herbo-ptsd-lyrics',
             'Lil-baby-and-42-dugg-grace-lyrics', 'Lil-baby-get-ugly-lyrics',
             'Lil-baby-and-moneybagg-yo-no-sucker-lyrics',
             'Lil-baby-how-lyrics',
             'Sza-and-justin-timberlake-the-other-side-lyrics',
             'Lil-baby-forever-lyrics', 'Lil-baby-same-thing-lyrics',
             'Lil-baby-and-young-thug-we-should-lyrics',
             'Surfaces-sunday-best-lyrics', 'Lil-baby-cant-explain-lyrics',
             'Lil-uzi-vert-baby-pluto-lyrics', 'Lil-uzi-vert-lo-mein-lyrics',
             'Lil-uzi-vert-silly-watch-lyrics', 'Lil-uzi-vert-p2-lyrics',
             'Demi-lovato-i-love-me-lyrics', 'Lil-uzi-vert-homecoming-lyrics',
             'Jhene-aiko-bs-lyrics', 'Lil-uzi-vert-prices-lyrics',
             'Lil-uzi-vert-pop-lyrics', 'Lil-uzi-vert-bigger-than-life-lyrics',
             'Lil-uzi-vert-celebration-station-lyrics',
             'Lil-uzi-vert-you-better-move-lyrics',
             'Lil-uzi-vert-im-sorry-lyrics', 'Lil-uzi-vert-venetia-lyrics',
             'Lil-uzi-vert-chrome-heart-tags-lyrics',
             'Lil-uzi-vert-bust-me-lyrics',
             'Jhene-aiko-happiness-over-everything-hoe-lyrics',
             'Lil-uzi-vert-secure-the-bag-lyrics',
             'Megan-thee-stallion-captain-hook-lyrics',
             'Lil-uzi-vert-urgency-lyrics', 'Gunna-skybox-lyrics',
             'Lil-yachty-and-dababy-oprahs-bank-account-lyrics',
             'Lil-uzi-vert-myron-lyrics', 'Lil-uzi-vert-bean-kobe-lyrics',
             'Lil-uzi-vert-and-21-savage-yessirskiii-lyrics',
             'Lil-uzi-vert-lotus-lyrics', 'Lil-uzi-vert-wassup-lyrics',
             'Lil-uzi-vert-strawberry-peels-lyrics',
             'Lil-uzi-vert-moon-relate-lyrics',
             'Lil-uzi-vert-i-can-show-you-lyrics',
             'Lil-uzi-vert-trap-this-way-this-way-lyrics',
             'Deathbed-by-powfu-ft-beabadoobee-death-bed-lyrics',
             'Lil-uzi-vert-leaders-lyrics', 'Lil-uzi-vert-no-auto-lyrics',
             'Lil-uzi-vert-come-this-way-lyrics',
             'Luke-combs-does-to-me-lyrics', 'Lil-uzi-vert-got-the-guap-lyrics',
             'Benee-supalonely-lyrics', 'Lil-uzi-vert-money-spread-lyrics',
             'Don-toliver-cardigan-lyrics', 'Thomas-rhett-beer-cant-fix-lyrics',
             'Megan-thee-stallion-savage-lyrics',
             'The-weeknd-in-your-eyes-lyrics', 'The-weeknd-alone-again-lyrics',
             'The-weeknd-scared-to-live-lyrics',
             'The-weeknd-hardest-to-love-lyrics', 'The-weeknd-too-late-lyrics',
             'The-weeknd-snowchild-lyrics', 'The-weeknd-escape-from-la-lyrics',
             'Ariana-grande-and-the-weeknd-save-your-tears-remix-lyrics',
             'The-weeknd-faith-lyrics', 'Saint-jhn-roses-lyrics',
             'The-weeknd-repeat-after-me-interlude-lyrics',
             'The-weeknd-until-i-bleed-out-lyrics',
             'Nle-choppa-walk-em-down-lyrics',
             'Kelsea-ballerini-the-other-girl-lyrics',
             'Nav-and-gunna-turks-lyrics', 'Dua-lipa-break-my-heart-lyrics',
             'Partynextdoor-and-rihanna-believe-it-lyrics',
             'Travis-denning-after-a-few-lyrics',
             'Florida-georgia-line-i-love-my-country-lyrics',
             'Sam-hunt-hard-to-forget-lyrics',
             'Kane-brown-and-john-legend-last-time-i-say-sorry-lyrics',
             'Jp-saxe-julia-michaels-and-friends-if-the-world-was-ending-lyrics',
             'Drake-toosie-slide-lyrics', 'Dababy-find-my-way-lyrics',
             'Rod-wave-fuck-the-world-lyrics', 'Rod-wave-pray-4-love-lyrics',
             'Thomas-rhett-be-a-light-lyrics',
             'Rod-wave-thief-in-the-night-lyrics', 'Future-tycoon-lyrics',
             'Rod-wave-i-remember-lyrics', 'Rod-wave-the-greatest-lyrics',
             'Miranda-lambert-bluebird-lyrics',
             'Rod-wave-ribbon-in-the-sky-lyrics',
             'Kenny-chesney-here-and-now-lyrics', 'Rod-wave-thug-life-lyrics',
             'Rod-wave-no-weakness-lyrics',
             'Twenty-one-pilots-level-of-concern-lyrics',
             'Tory-lanez-stupid-again-lyrics', 'Selena-gomez-boyfriend-lyrics',
             'Tory-lanez-broke-in-a-minute-lyrics',
             'Maddie-and-tae-die-from-a-broken-heart-lyrics',
             'Polo-g-dnd-lyrics', 'Scotty-mccreery-in-between-lyrics',
             'Regard-ride-it-lyrics', 'Rod-wave-girl-of-my-dreams-lyrics',
             'Doja-cat-boss-bitch-lyrics',
             'Dababy-ft-roddyricch-rockstar-lyrics', 'Dababy-jump-lyrics',
             'Playboi-carti-meh-lyrics',
             'Sam-smith-and-demi-lovato-im-ready-lyrics',
             'Dababy-pick-up-lyrics', 'Dababy-nasty-lyrics',
             'Dababy-lightskin-shit-lyrics',
             'Morgan-wallen-more-than-my-hometown-lyrics',
             'Dababy-cant-stop-lyrics', 'Dababy-blame-it-on-baby-lyrics',
             'Dababy-sad-shit-lyrics', 'Dababy-drop-lyrics',
             'Dababy-talk-about-it-lyrics', 'Dababy-champion-lyrics',
             'Kelly-clarkson-i-dare-you-lyrics',
             'Don-toliver-after-party-lyrics',
             'Keith-urban-god-whispered-your-name-lyrics',
             'The-scotts-the-scotts-lyrics', 'Juice-wrld-righteous-lyrics',
             'Lil-baby-all-in-lyrics', 'Travis-scott-goosebumps-lyrics',
             'Lil-uzi-vert-sasuke-lyrics', 'Kane-brown-cool-again-lyrics',
             'Youngboy-never-broke-again-aint-easy-lyrics',
             'Staysolidrocky-party-girl-lyrics',
             'Youngboy-never-broke-again-diamonds-lyrics',
             'Youngboy-never-broke-again-bout-my-business-lyrics',
             'Youngboy-never-broke-again-rough-ryder-lyrics',
             'Carrie-underwood-drinking-alone-lyrics',
             'Youngboy-never-broke-again-thug-of-spades-lyrics',
             'Drake-pain-1993-lyrics', 'Drake-chicago-freestyle-lyrics',
             'Future-drake-and-young-thug-d4l-lyrics',
             'Drake-not-you-too-lyrics', 'Drake-desires-lyrics',
             'Marshmello-and-halsey-be-kind-lyrics', 'Drake-time-flies-lyrics',
             'Drake-deep-pockets-lyrics', 'Drake-demons-lyrics',
             'Drake-when-to-say-when-lyrics', 'Drake-landed-lyrics',
             'Drake-from-florida-with-love-lyrics', 'Drake-losses-lyrics',
             'Drake-war-lyrics', 'Luke-combs-six-feet-apart-lyrics',
             'Lil-baby-and-42-dugg-we-paid-lyrics',
             'Lil-baby-social-distancing-lyrics', 'Lil-baby-low-down-lyrics',
             'Lil-baby-humble-lyrics', 'Luke-bryan-one-margarita-lyrics',
             'Young-t-and-bugsey-dont-rush-lyrics',
             'Ariana-grande-and-justin-bieber-stuck-with-u-lyrics',
             '6ix9ine-gooba-lyrics', 'Lil-durk-3-headed-goat-lyrics',
             'Kehlani-can-i-lyrics', 'Lil-tjay-zoo-york-lyrics',
             'Kehlani-toxic-lyrics',
             'Chris-brown-and-young-thug-go-crazy-lyrics',
             'Kehlani-change-your-life-lyrics', 'Moneybagg-yo-me-vs-me-lyrics',
             'Lil-durk-viral-moment-lyrics', 'Polo-g-flex-lyrics',
             'Future-solitaires-lyrics', 'Jonas-brothers-x-lyrics',
             'Future-trillionaire-lyrics', 'Katy-perry-daisies-lyrics',
             'Future-trapped-in-the-sun-lyrics', 'Future-all-bad-lyrics',
             'Polo-g-be-something-lyrics', 'Polo-g-martin-and-gina-lyrics',
             'Polo-g-21-lyrics', 'Future-hard-to-choose-one-lyrics',
             'Future-ridin-strikers-lyrics', 'Future-hitek-tek-lyrics',
             'Future-too-comfortable-lyrics',
             'Future-posted-with-demons-lyrics', 'Future-touch-the-sky-lyrics',
             'Future-one-of-my-lyrics', 'Future-harlem-shake-lyrics',
             'Polo-g-dont-believe-the-hype-lyrics',
             'Polo-g-beautiful-pain-losin-my-mind-lyrics', 'Polo-g-33-lyrics',
             'Polo-g-i-know-lyrics',
             'Lady-gaga-and-ariana-grande-rain-on-me-lyrics',
             'Gunna-dollaz-on-my-head-lyrics',
             'Gunna-cooler-than-a-bitch-lyrics', 'Gunna-top-floor-lyrics',
             'Gunna-wunna-lyrics', 'Gunna-blindfold-lyrics',
             'Migos-need-it-lyrics', 'Gunna-argentina-lyrics',
             'Gunna-met-gala-lyrics', 'Gunna-nasty-girl-on-camera-lyrics',
             'Gunna-motw-lyrics', 'Gunna-gimmick-lyrics',
             'Gunna-feigning-lyrics', 'Surf-mesa-ily-i-love-you-baby-lyrics',
             'Lady-gaga-and-blackpink-sour-candy-lyrics',
             'Juice-wrld-and-trippie-redd-tell-me-u-luv-me-lyrics',
             'Jason-aldean-got-what-i-got-lyrics',
             'Locash-one-big-country-song-lyrics',
             'Lil-yachty-and-tierra-whack-td-lyrics', 'Lady-gaga-alice-lyrics',
             'Justin-moore-why-we-drink-lyrics',
             'Kygo-and-onerepublic-lose-somebody-lyrics',
             'Lee-brice-one-of-them-girls-lyrics', 'Doja-cat-like-that-lyrics',
             'Hardy-one-beer-lyrics', 'Meek-mill-otherside-of-america-lyrics',
             'Sleepy-hallow-deep-end-freestyle-lyrics',
             'Black-eyed-peas-ozuna-and-j-rey-soul-mamacita-lyrics',
             'Ashley-mcbryde-one-night-standards-lyrics',
             'Brantley-gilbert-hard-days-lyrics',
             'Kane-brown-worldwide-beautiful-lyrics',
             '6ix9ine-and-nicki-minaj-trollz-lyrics',
             'Lil-baby-the-bigger-picture-lyrics',
             'Pop-smoke-make-it-rain-lyrics',
             'The-kid-laroi-and-juice-wrld-go-lyrics',
             'Nle-choppa-shotta-flow-5-lyrics',
             'J-cole-snow-on-tha-bluff-lyrics', 'Tyla-yaweh-tommy-lee-lyrics',
             'Jawsh-685-jason-derulo-and-bts-savage-love-laxed-siren-beat-bts-remix-lyrics',
             'Chloe-x-halle-do-it-lyrics', 'Chris-janson-done-lyrics',
             'Zac-brown-band-the-man-who-loves-you-the-most-lyrics',
             'Ji-the-prince-of-ny-need-me-lyrics',
             'Beyonce-black-parade-lyrics',
             'A-boogie-wit-da-hoodie-bleed-lyrics', 'Breland-my-truck-lyrics',
             'Youngboy-never-broke-again-one-shot-lyrics',
             'Parker-mccollum-pretty-heart-lyrics', 'Ajr-bang-lyrics',
             'Megan-thee-stallion-girls-in-the-hood-lyrics',
             'Blackpink-how-you-like-that-lyrics',
             'Kanye-west-wash-us-in-the-blood-lyrics',
             '6lack-know-my-rights-lyrics',
             'Trevor-daniel-and-selena-gomez-past-life-lyrics',
             'Eric-church-stick-that-in-your-country-song-lyrics',
             'Luke-combs-lovin-on-you-lyrics', 'Rod-wave-rags2riches-lyrics',
             'Tim-mcgraw-i-called-mama-lyrics',
             'Pop-smoke-for-the-night-lyrics', 'Pop-smoke-the-woo-lyrics',
             'Pop-smoke-got-it-on-me-lyrics',
             'Pop-smoke-aim-for-the-moon-lyrics', 'Pop-smoke-gangstas-lyrics',
             'Pop-smoke-44-bulldog-lyrics',
             'Pop-smoke-something-special-lyrics', 'Pop-smoke-yea-yea-lyrics',
             'Pop-smoke-mood-swings-lyrics',
             'Pop-smoke-what-you-know-bout-love-lyrics',
             'Pop-smoke-snitching-lyrics',
             'Pop-smoke-bad-bitch-from-tokyo-intro-lyrics',
             'Pop-smoke-enjoy-yourself-lyrics', 'Pop-smoke-creature-lyrics',
             'Moneybagg-yo-said-sum-lyrics', 'Pop-smoke-west-coast-shit-lyrics',
             'Juice-wrld-and-halsey-lifes-a-mess-lyrics',
             'Pop-smoke-diana-lyrics', 'Pop-smoke-tunnel-vision-outro-lyrics',
             'Juice-wrld-and-marshmello-come-and-go-lyrics',
             'Juice-wrld-wishing-well-lyrics',
             'Juice-wrld-conversations-lyrics',
             'Juice-wrld-and-marshmello-hate-the-other-side-lyrics',
             'Juice-wrld-blood-on-my-jeans-lyrics', 'Juice-wrld-titanic-lyrics',
             'Juice-wrld-bad-energy-lyrics',
             'Kid-cudi-and-eminem-the-adventures-of-moon-man-and-slim-shady-lyrics',
             'Juice-wrld-stay-high-lyrics', 'Juice-wrld-fighting-demons-lyrics',
             'Juice-wrld-up-up-and-away-lyrics',
             'Juice-wrld-screw-juice-lyrics', 'Juice-wrld-i-want-it-lyrics',
             'Juice-wrld-cant-die-lyrics', 'Juice-wrld-man-of-the-year-lyrics',
             'Kane-brown-swae-lee-and-khalid-be-like-that-lyrics',
             'Summer-walker-let-it-go-lyrics',
             'Summer-walker-and-partynextdoor-my-affection-lyrics',
             'Saweetie-tap-in-lyrics', 'Dj-khaled-popstar-lyrics',
             'Dj-khaled-greece-lyrics', 'Topic-and-a7s-breaking-me-lyrics',
             'J-cole-t-h-e-c-l-i-m-b-b-a-c-k-lyrics',
             'Taylor-swift-cardigan-lyrics', 'Taylor-swift-the-1-lyrics',
             'Taylor-swift-exile-lyrics',
             'Taylor-swift-the-last-great-american-dynasty-lyrics',
             'Taylor-swift-my-tears-ricochet-lyrics',
             'Taylor-swift-august-lyrics', 'Taylor-swift-mirrorball-lyrics',
             'Taylor-swift-seven-lyrics',
             'Taylor-swift-invisible-string-lyrics',
             'Taylor-swift-this-is-me-trying-lyrics',
             'Taylor-swift-betty-lyrics', 'Taylor-swift-illicit-affairs-lyrics',
             'Maroon-5-nobodys-love-lyrics', 'Taylor-swift-mad-woman-lyrics',
             'J-cole-lion-king-on-ice-lyrics',
             'Blake-shelton-happy-anywhere-lyrics',
             'Taylor-swift-epiphany-lyrics', 'Taylor-swift-peace-lyrics',
             'J-balvin-dua-lipa-bad-bunny-and-tainy-un-dia-one-day-lyrics',
             'Taylor-swift-hoax-lyrics', 'Logic-perfect-lyrics',
             'Billie-eilish-my-future-lyrics', 'A-ap-ferg-move-ya-hips-lyrics',
             'Dan-shay-i-should-probably-go-to-bed-lyrics',
             'Dababy-no-dribble-lyrics', 'Cardi-b-wap-lyrics',
             'Juice-wrld-and-the-weeknd-smile-lyrics',
             'Rod-wave-letter-from-houston-lyrics',
             'Ava-max-kings-and-queens-lyrics',
             'Machine-gun-kelly-and-blackbear-my-exs-best-friend-lyrics',
             '24kgoldn-mood-lyrics', 'Rod-wave-freestyle-lyrics',
             'Jameson-rodgers-some-girls-lyrics',
             'Latto-bitch-from-da-souf-lyrics',
             'Drake-laugh-now-cry-later-lyrics',
             'Morgan-wallen-7-summers-lyrics',
             'Miley-cyrus-midnight-sky-lyrics',
             'Youngboy-never-broke-again-kacey-talk-lyrics',
             'Conan-gray-heather-lyrics', 'Internet-money-lemonade-lyrics',
             'Money-man-24-remix-lyrics', 'Chase-rice-lonely-if-you-are-lyrics',
             'Bts-dynamite-lyrics', 'Travis-scott-the-plan-lyrics',
             'Youngboy-never-broke-again-all-in-lyrics',
             'Tate-mcrae-you-broke-me-first-lyrics', 'Nas-spicy-lyrics',
             'Blackpink-and-selena-gomez-ice-cream-lyrics',
             'Calvin-harris-and-the-weeknd-over-now-lyrics',
             'Chris-stapleton-starting-over-lyrics',
             'Internet-money-blastoff-lyrics', 'Ty-dolla-sign-expensive-lyrics',
             'Whoheem-lets-link-lyrics',
             'Jon-pardi-aint-always-the-cowboy-lyrics',
             'Sza-hit-different-lyrics', 'Lil-durk-the-voice-lyrics',
             'Big-sean-wolves-lyrics', 'Big-sean-lithuania-lyrics',
             'Big-sean-deep-reverence-lyrics',
             'Russell-dickerson-love-you-like-i-used-to-lyrics',
             'Big-sean-body-language-lyrics',
             'Matt-stell-everywhere-but-on-lyrics',
             'Big-sean-why-would-i-stop-lyrics',
             'Youngboy-never-broke-again-my-window-lyrics',
             'Marshmello-and-demi-lovato-ok-not-to-be-ok-lyrics',
             'Youngboy-never-broke-again-drug-addiction-lyrics',
             'Andrew-jannakos-gone-too-soon-lyrics',
             'Youngboy-never-broke-again-dead-trollz-lyrics',
             'Youngboy-never-broke-again-cross-roads-lyrics',
             'Youngboy-never-broke-again-the-last-backyard-lyrics',
             'Youngboy-never-broke-again-right-foot-creep-lyrics',
             'Vedo-you-got-it-lyrics',
             'Youngboy-never-broke-again-dirty-stick-lyrics',
             'Justin-bieber-holy-lyrics', 'Sam-smith-diamonds-lyrics',
             'Keith-urban-and-p-nk-one-too-many-lyrics',
             'Luke-combs-without-you-lyrics',
             'Lil-tecca-and-lil-uzi-vert-dolly-lyrics',
             'Lil-tecca-and-polo-g-when-you-down-lyrics',
             'Yfn-lucci-wet-she-got-that-lyrics',
             'Sada-baby-whole-lotta-choppas-remix-lyrics',
             'Dababy-blind-lyrics', 'Travis-scott-franchise-lyrics',
             'Machine-gun-kelly-forget-me-too-lyrics', 'Polo-g-epidemic-lyrics',
             'Machine-gun-kelly-bloody-valentine-lyrics',
             'Ne-yo-and-jeremih-u-2-luv-lyrics', 'Zayn-better-lyrics',
             'Machine-gun-kelly-drunk-face-lyrics',
             'Chris-lane-big-big-plans-lyrics', 'Niko-moon-good-time-lyrics',
             'Ritt-momney-put-your-records-on-lyrics',
             'Tory-lanez-money-over-fallouts-lyrics',
             '21-savage-and-metro-boomin-runnin-lyrics',
             '21-savage-and-metro-boomin-mr-right-now-lyrics',
             'Shawn-mendes-wonder-lyrics',
             '21-savage-and-metro-boomin-glock-in-my-lap-lyrics',
             'Fleetwood-mac-dreams-lyrics',
             '21-savage-and-metro-boomin-rich-nigga-shit-lyrics',
             'Megan-thee-stallion-dont-stop-lyrics',
             '21-savage-and-metro-boomin-slidin-lyrics',
             '21-savage-and-metro-boomin-many-men-lyrics',
             'Why-dont-we-fallin-adrenaline-lyrics',
             'Bryson-tiller-outta-time-lyrics',
             '21-savage-and-metro-boomin-my-dawg-lyrics',
             '21-savage-and-metro-boomin-brand-new-draco-lyrics',
             'Blackpink-lovesick-girls-lyrics',
             '21-savage-and-metro-boomin-snitches-and-rats-lyrics',
             '21-savage-and-metro-boomin-no-opp-left-behind-lyrics',
             'Dua-lipa-levitating-feat-dababy-kuu-remix-lyrics',
             '21-savage-and-metro-boomin-steppin-on-niggas-lyrics',
             '21-savage-and-metro-boomin-rip-luv-lyrics',
             'Bryson-tiller-always-forever-lyrics',
             'Bryson-tiller-years-go-by-lyrics',
             '21-savage-and-metro-boomin-said-n-done-lyrics',
             'Bebe-rexha-baby-im-jealous-lyrics',
             'Kelsea-ballerini-hole-in-the-bottle-lyrics',
             'Clairo-sofia-lyrics',
             'Justin-bieber-and-benny-blanco-lonely-lyrics',
             'Yung-bleu-youre-mines-still-remix-lyrics',
             'G-eazy-hate-the-way-lyrics', 'Larray-canceled-lyrics',
             'Kenny-chesney-happy-does-lyrics',
             'Brs-kash-throat-baby-go-baby-lyrics', 'Ti-pardon-lyrics',
             'Lady-a-champagne-night-from-songland-lyrics',
             'Ariana-grande-positions-lyrics',
             'Luke-combs-forever-after-all-lyrics',
             'Jack-harlow-tyler-herro-lyrics', 'Ty-dolla-sign-spicy-lyrics',
             'Luke-combs-the-other-guy-lyrics', 'Her-damage-lyrics',
             'Saweetie-back-to-the-streets-lyrics',
             'The-kid-laroi-so-done-lyrics', 'Luke-combs-cold-as-you-lyrics',
             'Dababy-practice-lyrics', 'Joel-corry-head-and-heart-lyrics',
             'Little-big-town-wine-beer-whiskey-lyrics',
             'Ariana-grande-34-35-lyrics',
             'Ariana-grande-and-doja-cat-motive-lyrics',
             'Ariana-grande-and-the-weeknd-off-the-table-lyrics',
             'Ariana-grande-pov-lyrics', 'Ariana-grande-just-like-magic-lyrics',
             'Ariana-grande-shut-up-lyrics', 'Ariana-grande-nasty-lyrics',
             'Ariana-grande-safety-net-lyrics',
             'Ariana-grande-six-thirty-lyrics', 'Ariana-grande-my-hair-lyrics',
             'Ariana-grande-obvious-lyrics', 'Ariana-grande-west-side-lyrics',
             'Ariana-grande-love-language-lyrics',
             'Trippie-redd-weeeeee-lyrics',
             'Lil-durk-6lack-and-young-thug-stay-down-lyrics',
             'Dj-chose-and-beatking-thick-lyrics',
             'Mike-will-made-it-nicki-minaj-and-youngboy-never-broke-again-what-that-speed-bout-lyrics',
             'King-von-took-her-to-the-o-lyrics',
             'Nav-dont-need-friends-lyrics', 'King-von-the-code-lyrics',
             'The-kid-laroi-tragic-lyrics', 'King-von-all-these-niggas-lyrics',
             'King-von-crazy-story-20-lyrics', 'The-kid-laroi-always-do-lyrics',
             'Nav-and-gunna-young-wheezy-lyrics',
             'Darius-rucker-beers-and-sunshine-lyrics',
             'Billie-eilish-therefore-i-am-lyrics',
             'The-kid-laroi-fck-you-goodbye-lyrics',
             'Future-and-lil-uzi-vert-drankin-n-smokin-lyrics',
             'Lil-nas-x-holiday-lyrics',
             'Future-and-lil-uzi-vert-stripes-like-burberry-lyrics',
             'Future-and-lil-uzi-vert-thats-it-lyrics',
             'Future-and-lil-uzi-vert-real-baby-pluto-lyrics',
             'Phoebe-and-maggie-iris-lyrics',
             'Future-and-lil-uzi-vert-marni-on-me-lyrics',
             'Future-and-lil-uzi-vert-million-dollar-play-lyrics',
             'Future-and-lil-uzi-vert-sleeping-on-the-floor-lyrics',
             'Thomas-rhett-whats-your-country-song-lyrics',
             'Future-and-lil-uzi-vert-plastic-lyrics',
             'Future-rockstar-chainz-lyrics',
             'Future-and-lil-uzi-vert-bought-a-bad-bitch-lyrics',
             'Shawn-mendes-and-justin-bieber-monster-lyrics',
             'Megan-thee-stallion-body-lyrics', 'Bts-stay-lyrics',
             'Morgan-wallen-somebodys-problem-lyrics',
             'Morgan-wallen-still-goin-down-lyrics',
             'Miley-cyrus-prisoner-lyrics', 'Bts-fly-to-my-room-lyrics',
             'Megan-thee-stallion-cry-baby-lyrics',
             'Megan-thee-stallion-shots-fired-lyrics',
             'Morgan-wallen-livin-the-dream-lyrics',
             'Meek-mill-pain-away-lyrics',
             'Megan-thee-stallion-do-it-on-the-tip-lyrics',
             'Megan-thee-stallion-circles-lyrics',
             'Morgan-wallen-cover-me-up-lyrics',
             'Michael-buble-its-beginning-to-look-a-lot-like-christmas-lyrics',
             'Trey-lewis-dicked-down-in-dallas-lyrics',
             'Kelly-clarkson-and-brett-eldredge-under-the-mistletoe-lyrics',
             'Justin-bieber-rockin-around-the-christmas-tree-lyrics',
             'Lil-baby-on-me-lyrics', 'Ariana-grande-santa-tell-me-lyrics',
             'Lil-baby-errbody-lyrics',
             'Paul-mccartney-wonderful-christmastime-lyrics',
             'The-kid-laroi-without-you-lyrics',
             'Benny-blanco-and-juice-wrld-real-shit-lyrics',
             'Mariah-carey-oh-santa-remix-lyrics',
             'Dan-shay-take-me-home-for-christmas-lyrics',
             'Carrie-underwood-and-john-legend-hallelujah-lyrics',
             'Carrie-underwood-silent-night-lyrics',
             'Taylor-swift-willow-lyrics',
             'Taylor-swift-champagne-problems-lyrics',
             'Taylor-swift-no-body-no-crime-lyrics',
             'Taylor-swift-tis-the-damn-season-lyrics',
             'Taylor-swift-gold-rush-lyrics', 'Kid-cudi-tequila-shots-lyrics',
             'Taylor-swift-tolerate-it-lyrics',
             'Kid-cudi-she-knows-this-lyrics', 'Taylor-swift-happiness-lyrics',
             'Kid-cudi-skepta-and-pop-smoke-show-out-lyrics',
             'Taylor-swift-evermore-lyrics', 'Taylor-swift-ivy-lyrics',
             'Taylor-swift-coney-island-lyrics', 'Kid-cudi-another-day-lyrics',
             'Taylor-swift-dorothea-lyrics',
             'Taylor-swift-long-story-short-lyrics',
             'Taylor-swift-cowboy-like-me-lyrics', 'Jack-harlow-way-out-lyrics',
             'Taylor-swift-marjorie-lyrics', 'Kid-cudi-mr-solo-dolo-iii-lyrics',
             'Kid-cudi-dive-lyrics', 'Taylor-swift-closure-lyrics',
             'Kid-cudi-heaven-on-earth-lyrics',
             'The-kid-laroi-and-juice-wrld-reminds-me-of-you-lyrics',
             'Kid-cudi-sad-people-lyrics', 'Kid-cudi-damaged-lyrics',
             'Kid-cudi-beautiful-trip-lyrics',
             'Bing-crosby-and-the-andrews-sisters-mele-kalikimaka-lyrics',
             'Donny-hathaway-this-christmas-lyrics',
             'Eagles-please-come-home-for-christmas-lyrics',
             'The-jackson-5-santa-claus-is-coming-to-town-lyrics',
             'The-beach-boys-little-saint-nick-1991-remix-lyrics',
             'Michael-buble-have-yourself-a-merry-little-christmas-lyrics',
             'Bing-crosby-ill-be-home-for-christmas-if-only-in-my-dreams-lyrics',
             'Ed-sheeran-afterglow-lyrics', 'Eminem-gnat-lyrics',
             'Gabby-barrett-the-first-noel-lyrics',
             'Popp-hunna-adderall-corvette-corvette-lyrics',
             'Lil-durk-backdoor-lyrics', 'Ddg-moonwalking-in-calabasas-lyrics']
    url = 'https://genius.com/'
    i = -1
    dont_filter = True

    def parse(self, response):
        yield {
            'genius_id': response.css("[property~='twitter:app:url:iphone']::attr(content)").get()
        }
        self.i += 1
        if self.i < len(self.songs):
            next_page_url = self.url + self.songs[self.i]
            yield scrapy.Request(next_page_url, self.parse)
        pass
